accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from .forms import UserLoginForm,PwdResetForm,PwdResetConfirmForm,PwdChangeForm
app_name='accounts'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html',
                                               authentication_form=UserLoginForm),
                                               name='login'),
                                               
    path('password_reset/',auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        form_class=PwdResetForm),name='pwdreset'),
    path('password_change/',auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        form_class=PwdChangeForm),name='pwdchange'),

    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        form_class=PwdResetConfirmForm),name='pwdresetconfirm'),

    path('profile/',views.profile,name='profile'),
    path('profile/edit/',views.edit,name='edit'),
    path('fav/<int:id>/', views.favourite_add, name='favourite_add'),
    path('profile/favourites/',views.favourite_list,name='favourite_list'),
    path('like/', views.like, name='like'),
    path('thumbs/', views.thumbs, name='thumbs'),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',views.activate,name='activate'),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('',views.home,name='homepage'),
    path('search/',views.postSearch,name='post_search'),
    path('<slug:post>/',views.post_single,name='post_single'),
    path('category/<category>/',views.CatListView.as_view(),name='category'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('account/',include('accounts.urls',namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel,TreeForeignKey

def user_directory_path(instance,filename):
    return 'posts/{0}/{1}'.format(instance.id,filename)

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')
    
    options=(('draft','Draft'),('published','Published'))
    category=models.ForeignKey(Category,on_delete=models.PROTECT,default=1)
    title=models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    image=models.ImageField(upload_to=user_directory_path,default='posts/default.jpg')
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    publish=models.DateTimeField(default=timezone.now)
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    content=models.TextField()
    status=models.CharField(max_length=10,choices=options,default='draft')
    favourites=models.ManyToManyField(User,related_name='favourite',default=None,blank=True)
    
    likes=models.ManyToManyField(User,related_name='likes',default=None,blank=True)
    like_count=models.IntegerField(default=0)
    
    thumbsup=models.IntegerField(default='0')
    thumbsdown=models.IntegerField(default='0')
    thumbs=models.ManyToManyField(User,related_name='thumbs',default=None,blank=True)
    
    objects=models.Manager()
    newmanager=NewManager()


    def get_absolute_url(self):
        return reverse('blog:post_single',args=[self.slug])

    class Meta:
        ordering=('publish',)

    def __str__(self):
        return self.title
    

class Comment(MPTTModel):

    name=models.CharField(max_length=100)
    parent=TreeForeignKey('self',on_delete=models.CASCADE,
                          null=True,blank=True,related_name='children')
    publish=models.DateTimeField(auto_now_add=True)
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    content=models.TextField()
    email=models.EmailField(default='default@example.com')
    status=models.BooleanField(default=True)
    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by=['publish']

        
class Vote(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='votes')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    vote=models.BooleanField(default=True)  # True for upvote, False for downvote

blog/forms.py
from django import forms
from .models import Comment,Category
from mptt.forms import TreeNodeChoiceField


class Newcomment(forms.ModelForm):
    parent=TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args,**kargs):
        super().__init__(*args,**kargs)
        self.fields['parent'].widget.attrs.update({'class':'d-none'})
        self.fields['parent'].label=''
        self.fields['parent'].required=False
    class Meta:

        model=Comment
        fields=('name','parent','email','content')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

class PostSearchForm(forms.Form):
    q=forms.CharField()    
    def __init__(self, *args,**kargs):
        super().__init__(*args,**kargs)
        self.fields['q'].label='Search For'
        self.fields['q'].widget.attrs.update({'class':'form-control'})
        self.fields['q'].widget.attrs.update({'data-toggle':'dropdown'})

blog/views.py
from django.shortcuts import render,get_object_or_404,HttpResponsePermanentRedirect
from .models import Post,Comment,Category
from .forms import Newcomment,PostSearchForm
from django.views.generic import ListView
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.db.models import Q
from django.http import JsonResponse
from django.core import serializers
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank
# Create your views here.


def home(request):

    posts=Post.newmanager.all()

    return render(request,'index.html',{'posts':posts})

def post_single(request,post):
    post=get_object_or_404(Post,slug=post,status='published')

    fav = bool

    if post.favourites.filter(id=request.user.id).exists():
        fav=True
    allcomments=post.comments.filter(status=True)
    page=request.GET.get('page',1)
    paginator=Paginator(allcomments,3)

    try:
        comments=paginator.page(page)
    except PageNotAnInteger:
        comments=paginator.page(1)
    except EmptyPage:
        comments=paginator.page(paginator.num_pages)

    user_comment=None
    if request.method == 'POST':
        comment_form=Newcomment(request.POST)
        if comment_form.is_valid():
            user_comment=comment_form.save(commit=False)
            user_comment.post=post
            user_comment.save()
            return HttpResponsePermanentRedirect('/'+post.slug)
    else:
        comment_form=Newcomment()

    return render(request,'single.html',
                  {'post':post,'user_comment':user_comment,
                   'comments':comments,'comment_form':comment_form,'allcomments':allcomments,'fav':fav})


class CatListView(ListView):
    template_name='category.html'
    context_object_name='catlist'

    def get_queryset(self):
        content={
            'cat':self.kwargs['category'],
            'posts':Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content


def category_list(request):
    category_list=Category.objects.exclude(name='default')
    context={
        "category_list":category_list,
    }
    return context

def postSearch(request):
    form=PostSearchForm()
    q=''
    # c=''
    results=[]
    query=Q()

    # if request.POST.get('action')=='post':
    #     search_string=str(request.POST.get('ss'))

    #     if search_string is not None:
    #         search_string=Post.objects.filter(title__contains=search_string)[:5]
    #         data=serializers.serialize('json',list(search_string),fields=('id','title','slug'))

    #     return JsonResponse({'search_string':data})
    
    if 'q' in request.GET:
        form=PostSearchForm(request.GET)
        if form.is_valid():
            q=form.cleaned_data['q']
            # c=form.cleaned_data['c']
            # if c is not None:
            #     query &=Q (category=c)
            # if q is not None:
                # query &= Q(title__contains=q)
            # results=Post.objects.filter(title__search=q)
            vector=SearchVector('title',weight='A') + \
                     SearchVector('content',weight='B')
            query=SearchQuery(q)
            results=Post.objects.annotate(rank=SearchRank(
                vector,query,cover_density=True)).order_by('-rank')
            # results=Post.objects.annotate(
            #     search=SearchVector('title','content'),
            #     ).filter(search=SearchQuery(q))


    return render(request,'search.html',
                  {'form':form,'q':q,
                   'results':results})

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome to blog {% endblock %}</title>

  </head>
  <body>
      <style>
        .avatar {
            height: 30px;
            width: 30px;
            background-color: #000;
            border-radius: 50%;
            display: inline-block;

        }
      </style>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
          <a class="nav-link" href="/search">Search</a>
        </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for category in category_list %}
                  <a class="dropdown-item" href="/category/{{ category.name}}">
                  {{ category.name|title }}
                  </a>
                {% endfor %}
              </div>
            </li>
          </ul>
          <div>
          {% if request.user.is_authenticated %}
          <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "accounts:profile" %}">
          <img class="avatar" src="
          {% for data in avatar %}
          {{ data.avatar.url }}
          {% endfor %}">
          </a>
          {% else %}
          <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "login" %}">Login</a>
          {% endif %}
          </div>
          <form class="form-inline my-2 my-lg-0" action="/search/" method="get">
        <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/category.html
 {% extends "base.html" %}

    {% block title %}
      Catlist
    {% endblock %}

    {% block content %}
    
       <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
        <div class="col-12 pb-5"><h1> List of {{catlist.cat}} posts</h1></div>
        {% for post in catlist.posts %}
            <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{post.title}}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
              </a>
            </div>
        {% endfor %}
          </div>
        </div>
      </div>

    {% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block title %}
Welcome to Blog
{% endblock %}

{% block content %}

<div class="container">

  <div class="row justify-content-md-center">

  <div class="col-md-8 pt-5">

  {% for post in posts %}
    <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{post.title}}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
              </a>
            </div>

  {% endfor %}

  </div>

  </div>

</div>

{% endblock %}

blog/templates/search.html
{% extends "base.html" %}

{% block title %}
Search
{% endblock %}

{% block content %}

{% if q %}
    <h1>Posts containing "{{ q }}"</h1>
    <p>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>

     <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in results %}
                <div class="col-md-4">
                    <a class="text-dark" href="{{post.get_absolute_url}}">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                                <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <p>There are no results for your query.</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <p><a href="{% url "blog:post_search" %}" class="btn btn-primary" role="button" aria-disabled="true">New
            Search</a>
    </p>
{% else %}
    <h1>Search for posts</h1>
    <form class="dropdown" method="get">
        {% csrf_token %}
        {{ form.q }}

         <ul class="dropdown-menu col-12 pl-2" role="menu" aria-labelledby="menu" id="list">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">seach for ?</a></li>
            <div class="dropdown-divider"></div>
        </ul>

        {{ form.c }}
        <input class="btn btn-primary my-1" type="submit" value="Search">
    </form>

    <script>
         $(document).on('keyup', '#id_q', function (e) {
        e.preventDefault();

        var minlength = 3;
        var results = [];

        if ($('#id_q').val().length >= minlength) {
            $.ajax({
                type: 'POST',
                url: '{% url "blog:post_search" %}',
                data: {
                    ss: $('#id_q').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {

                    $.each(JSON.parse(json.search_string), function (i, item) {

                        results.push('<li class="my-2 pl-2"><a href="/' + item
                            .fields.slug +
                            '">' + item.fields.title +
                            '</a></li>')
                    })

                    if (!$(".show")[0]) {
                        $('.menudd').trigger('click')
                    }

                    document.getElementById("list").innerHTML = (!results.length) ?
                        "No results match your query" : results.join('');
                },
                error: function (xhr, errmsg, err) {}
            });
        }
    })
    </script>
{% endif %}
{% endblock %}